site_name: Placeholder
site_url: http://blabla.com
site_author: Diego Veiga

nav:
  - Home: index.md
  - Resume: resume/index.md
  - Projects: projects/index.md

theme:
  name: material
  language: pt-BR
  features:
    - navigation.scroll
    - navigation.mobile
  palette:
    - scheme: slate
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Modo claro
    - scheme: default
      primary: light green
      toggle:
        icon: material/weather-night
        name: Modo noturno
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search
  - badges